# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cheng/fctree

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cheng/fctree

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cheng/fctree/CMakeFiles /home/cheng/fctree//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cheng/fctree/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named firmcore_baseline

# Build rule for target.
firmcore_baseline: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 firmcore_baseline
.PHONY : firmcore_baseline

# fast build rule for target.
firmcore_baseline/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmcore_baseline.dir/build.make CMakeFiles/firmcore_baseline.dir/build
.PHONY : firmcore_baseline/fast

#=============================================================================
# Target rules for targets named CoreIndexParallelLib

# Build rule for target.
CoreIndexParallelLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CoreIndexParallelLib
.PHONY : CoreIndexParallelLib

# fast build rule for target.
CoreIndexParallelLib/fast:
	$(MAKE) $(MAKESILENT) -f CoreIndexParallel/CMakeFiles/CoreIndexParallelLib.dir/build.make CoreIndexParallel/CMakeFiles/CoreIndexParallelLib.dir/build
.PHONY : CoreIndexParallelLib/fast

#=============================================================================
# Target rules for targets named CoreParallelNewLib

# Build rule for target.
CoreParallelNewLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CoreParallelNewLib
.PHONY : CoreParallelNewLib

# fast build rule for target.
CoreParallelNewLib/fast:
	$(MAKE) $(MAKESILENT) -f CoreParallelNew/CMakeFiles/CoreParallelNewLib.dir/build.make CoreParallelNew/CMakeFiles/CoreParallelNewLib.dir/build
.PHONY : CoreParallelNewLib/fast

#=============================================================================
# Target rules for targets named CoreParallelLib

# Build rule for target.
CoreParallelLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CoreParallelLib
.PHONY : CoreParallelLib

# fast build rule for target.
CoreParallelLib/fast:
	$(MAKE) $(MAKESILENT) -f CoreParallel/CMakeFiles/CoreParallelLib.dir/build.make CoreParallel/CMakeFiles/CoreParallelLib.dir/build
.PHONY : CoreParallelLib/fast

#=============================================================================
# Target rules for targets named CoreLib

# Build rule for target.
CoreLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CoreLib
.PHONY : CoreLib

# fast build rule for target.
CoreLib/fast:
	$(MAKE) $(MAKESILENT) -f Core/CMakeFiles/CoreLib.dir/build.make Core/CMakeFiles/CoreLib.dir/build
.PHONY : CoreLib/fast

#=============================================================================
# Target rules for targets named GraphLib

# Build rule for target.
GraphLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GraphLib
.PHONY : GraphLib

# fast build rule for target.
GraphLib/fast:
	$(MAKE) $(MAKESILENT) -f Graph/CMakeFiles/GraphLib.dir/build.make Graph/CMakeFiles/GraphLib.dir/build
.PHONY : GraphLib/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmcore_baseline.dir/build.make CMakeFiles/firmcore_baseline.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmcore_baseline.dir/build.make CMakeFiles/firmcore_baseline.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/firmcore_baseline.dir/build.make CMakeFiles/firmcore_baseline.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CoreIndexParallelLib"
	@echo "... CoreLib"
	@echo "... CoreParallelLib"
	@echo "... CoreParallelNewLib"
	@echo "... GraphLib"
	@echo "... firmcore_baseline"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

